{
	"references": {
		"math": {
			"aussagen": [
				"Eine Aussage ist ein Satz, der entweder wahr oder falsch ist, also nie beides zugleich. Wahre Aussagen haben den Wahrheitswert w und falsche Aussagen den Wahrheitswert f.",
				"Seien `p` und `q` Aussagen. Dann ist auch „p und q“ – dargestellt durch `(p ^^ q)` – eine Aussage, die so genannte (logische) Konjunktion. ist genau dann wahr, wenn sowohl `p` als auch `q` wahr ist.",
				"Seien `p` und `q` Aussagen. Dann ist auch „p oder q“ – dargestellt durch `(p vv q)` – eine Aussage, die so genannte(logische) Disjunktion.`(p ^^ q)` ist genau dann wahr, wenn `p` wahr ist, oder wenn `q` wahr ist, oder wenn `p` und `q` beide wahr sind.",
				"Sei `p` eine Aussage. Dann ist auch ”nicht p“ – dargestellt durch `(not p)` – eine Aussage, die so genannte (logische)notation. DieAussage `(not p)` ist genau dann wahr, wenn `p` falsch ist.",
				"Seien `p` und `q` Aussagen. Dann ist auch ”wenn `P` dann q“ – dargestellt durch `(p = > q)` – eine Aussage, die so genannte(logische)Implikation. Die Aussage `(p = > q)` ist genau dann falsch, wenn `p` wahr und `q` falsch ist.",
				"Seien `p` und `q` Aussagen. Dann ist auch ”p genau dann, wenn q“ – dargestellt durch `(p iff q)` – eine Aussage, die sogenannte (logische)Äquivalenz. Die Aussage `(p iff q)` ist genau dann wahr, wenn `p` und `q` beide den gleichen Wahrheitswert haben.",
				"Eine Tautologie ist eine Formel, die stets wahr ist, in deren Wahrheitswerteverlauf also ausschließlich derWahrheitswert w vorkommt. Eine Kontradiktion ist eine Formel, die stets falsch ist, in deren Wahrheitswerteverlauf alsoausschließlich der Wahrheitswert f vorkommt.",
				"Zwei Formeln `p` und `q` heißen (logisch) äquivalent – dargestellt durch `p equiv q` – genau dann, wenn die Formel `p iff q`eine Tautologie ist. DieFormel `p` wird von der Formel `q` impliziert genau dann, wenn `(p = > q)` eine Tautologie ist.",
				"Eine Aussageform über den Universen ist ein Satz mit den freien Variablen , der zu einer Aussage wird, wenn jedes durchein Element aus ersetzt wird.",
				"Sei `p(x)` eine Aussageform über dem Universum `U` . `exists x : p(x)` bezeichnet die Aussage, die aus der Aussageform`p(x)` durch die Quantifizierung ”Es gibt ein `u` in `U`, für das die Aussage `p(u)` gilt“ hervorgeht. `exists x : p(x)` ist wahr genau dann, wenn ein `u` in `U` existiert, so dass `p(u)` wahr ist.`forall x : p(x)` bezeichnet die Aussage, die aus der Aussageform `p(x)` durch die Quantifizierung ”Für jedes `u` aus `U`gilt `p(u)`“ hervorgeht. `forall x : p(x)` ist wahr genau dann, wenn `p(u)` für jedes `u` aus `U` wahr ist.",
				"<table class=\"table table-condensed table-striped\">\n\t<caption>Äquivalenzumformungen</caption>\n\t<thead>\n\t<tr>\n\t\t<td>Name</td>\n\t\t<td>Vereinfachung</td>\n\t</tr>\n\t</thead>\n\t<tbody>\n\t<tr>\n\t\t<td>Kommutativität</td>\n\t\t<td>`p ^^ q equiv q ^^ p`<br>\n\t\t    `p vv q equiv q vv p`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Assoziativität</td>\n\t\t<td>`p ^^ (q ^^ r) equiv (p ^^ q) ^^ r`<br>\n\t\t    `p ∨ (q ∨ r) equiv (p vv q) vv r`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Distributivität</td>\n\t\t<td>`p ^^ (q vv r) equiv (p ^^ q) vv (p ^^ r)`<br>\n\t\t    `p vv (q ^^ r) equiv (p vv q) ^^ (p vv r)`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Idempotenz</td>\n\t\t<td>`p ^^ p equiv p`<br>\n\t\t    `p vv p equiv p`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Doppelnegation</td>\n\t\t<td>`not(not p) equiv p`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Absorptionsgesetz</td>\n\t\t<td>`p ^^ (p vv q) = p`<br>\n\t\t\t`p vv (p ^^ q) = p`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td><s>Name</s></td>\n\t\t<td>`p => q equiv not p vv q`</td>\n\t</tr>\n\t<tr>\n\t\t<td>De Morgan</td>\n\t\t<td>`not(p ^^ q) equiv not p vv not q`<br>\n\t\t    `not(p vv q) equiv not p ^^ not q`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Tautologieregeln</td>\n\t\t<td>Falls q eine Tautologie ist, gilt:<br>\n\t\t    `p ^^ q equiv p`<br>\n\t\t    `p vv q equiv q`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Kontradiktionsregeln</td>\n\t\t<td>Falls q eine Kontradiktion ist, gilt:<br>\n\t\t    `p vv q equiv p`<br>\n\t\t    `p ^^ q equiv q`\n\t\t</td>\n\t</tr>\n\t</tbody>\n</table>"
			],

			"mengen": [
				"Zwei Mengen `A` und `B` sind gleich (bezeichnet durch `A = B` genau dann, wenn jedes Element von `A` auch Element von `B` ist und jedes Element von `B` auch Element von `A` ist.",
				"Sei `E(x)` eine Aussagenform über der Menge `U`. Dann heißen die Mengen `M = {x in U | E(x)}` und ( overline M = lbrace x in U mid neg E(x) rbrace ) in `U` komplementär. ( overline M) heißt Komplementärmenge oder Komplement von `M` in `U`.",
				"Die Menge, die kein Element enthält, heißt leere Menge und wird mit `O/` bezeichnet.",
				"Seien `A` und `B` Mengen. `A` heißt Teilmenge von `B` (dargestellt als `A sube B`) genau dann, wenn jedes Element von `A` auch element von `B` ist. In der Sprache der formalen Logik gilt: `(A sube B) equiv (forall x: x in A = > x in B)`.",
				"Sei `M` eine Menge. Dann ist `P(M) = {N | N ⊆ M}` die Potenzmenge von `M`. Wegen `∅ ⊆ M` und `M ⊆ M` für jede Menge `M` , gilt stets `∅  ∈ P ( M )` und `M ∈ P(M)`. Ist `M` endlich, so istauch `P(M)` endlich.",
				"<p>Sei `M` eine Menge und `P(M)` ihre Potenzmenge.\n   Für zwei Mengen `A` und `B` aus `P(M)` gibt es folgende Mengenfamilien zwischen `A` und `B`:</p>\n\n<table class=\"table table-striped table-condensed\">\n\t<caption>Intervalle</caption>\n\t<thead>\n\t<tr>\n\t\t<td>Offenes:</td>\n\t\t<td>`(A,B) = {N in P(M)&nbsp;|&nbsp;A sub N sub B}`</td>\n\t</tr>\n\t</thead>\n\t<tbody>\n\t<tr>\n\t\t<td>Abgeschlossenes:</td>\n\t\t<td>`[A,B] = {N in P(M)&nbsp;|&nbsp;A sube N sube B}`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Links Abgeschlossenes:</td>\n\t\t<td>`[A,B) = {N in P(M)&nbsp;|&nbsp;A sube N sub B}`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Rechts Abgeschlossenes:</td>\n\t\t<td>`(A,B] = {N in P(M)&nbsp;|&nbsp;A sub N sube B}`</td>\n\t</tr>\n\t</tbody>\n</table>",
				"Seien `M` und `N` zwei beliebige Mengen.<ol><li>Die Gesamtheit aller Elemente, die zu wenigstens einer der beiden Mengen `M` oder `N` gehören, bildet eine Menge,die als Vereinigung von `M` und `N` – dargestellt durch `M uu N` – bezeichnet wird. In der Sprache der formalenLogik gilt `M uu N = {x | (x in M) vv (x in N)}`.</li><li>Die Gesamtheit aller Element, die sowohl zu `M` als auch zu `N` gehören, bildet eine Menge, die als Durchschnitt von`M` und `N` - dargestellt durch `M nn N` - bezeichnet wird, `M nn N = {x | (x in M) ^^ (x in N)}`.</li><li>Die Gesamtheit aller Elemente, die zur Menge `M` gehören, aber nicht zur Menge `N`, bildet eine Menge, die alsDifferenz von `M` und `N` bezeichnet wird: `M - N = {x | (x in M) ^^ (x !in N)}`.</li></ol>",
				"Sei `M` eine Menge und `F sube P(M)`.<br>Die Menge `uuu F = {x | exists N : (N in F ^^ x in N)}` heißt Vereinigung aller Mengen aus F.<br>Die Menge `nnn F = {x | forall N : (N in F = > x in N)} nn uuu F` heißt Durchschnitt aller Mengen aus F.<br>Das Universum der beiden verwendeten Aussageformen `N in F ^^ x in N` und `N in F = > x in N` mit der freien Variablen `N`ist `P(M)`.",
				"Seien `M` und `N` zwei nicht notwendig verschiedene Mengen. Dann ist die Gesamtheit aller geordneten Paare `(m, n)` mit`m in M` und `n in N` eine Menge, die (kartesisches oder direktes) Produkt von `M` und `N` genannt.<br>`M xx N = {(m, n) | m in M ^^ n in N }`<br>Für den Spezialfall der leeren Menge gilt also `M xx O/ = O/`, `O/ xx N = O/`.",
				"Seien `M_1, …, M_t` Mengen. Das Produkt von `M_1, …, M_t` wird durch `M1 xx … xx Mt` bezeichnet und ist die Menge, die ausallen geordneten t-Tupeln `(m_1, …,m_t)` mit `m_i in M_i, i = 1, …, t` besteht:<br>`M_1 xx … xx M_t = {(m_1, …, m_t) | m_1 in M_1 ^^ … ^^ m_t in M_t}`<br>Gilt `M_1 = M_2 = … = M_t = M`, dann schreibt man anstelle des langenAusdrucks `M xx M xx … xx M` kurz `M_t`, wobei `M_0` in dieser Schreibweise die leere Menge bezeichnet und `M_1` die Menge`M`selbst.",
				"<p>Die Vereinigung der Produktmengen `M^0, M^1, …, M^n, …` wird mit `M^∗` bezeichnet: `M^∗ = uuu_(0 <= i) M^i`</p>\n\n<table class=\"table table-striped table-condensed\">\n\t<thead>\n\t<tr>\n\t\t<td>Name</td>\n\t\t<td>Vereinfachung</td>\n\t</tr>\n\t</thead>\n\t<tbody>\n\t<tr>\n\t\t<td>Kommutativität</td>\n\t\t<td>`A nn B = B nn A`<br>\n\t\t    `A uu B = B uu A`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Assoziativität</td>\n\t\t<td>`A nn (B nn C) = (A nn B) nn C`<br>\n\t\t    `A uu (B uu C) = (A uu B) uu C`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Distributivität</td>\n\t\t<td>`A nn (B uu C) = (A nn B) uu (A nn C)`<br>\n\t\t    `A uu (B nn C) = (A uu B) nn (A uu C)`<br>\n\t\t    `A xx (B uu C) = (A xx B) uu (A xx C)`<br>\n\t\t    `A xx (B nn C) = (A xx B) nn (A xx C)`<br>\n\t\t    `(A xx B) nn (C xx D) = (A nn C) xx (B nn D)`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Idempotenz</td>\n\t\t<td>`A nn A = A`<br>\n\t\t    `A uu A = A`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Doppelnegation</td>\n\t\t<td>\\( \\overline{(\\overline{A})} = A \\)</td>\n\t</tr>\n\t<tr>\n\t\t<td>De Morgan</td>\n\t\t<td>\\( \\overline{(A \\cap B)} = \\overline A \\cup \\overline B \\)<br>\n\t\t    \\( \\overline{(A \\cup B)} = \\overline A \\cap \\overline B \\)\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Absorption</td>\n\t\t<td>falls \\(A \\subseteq B \\):<br>\n\t\t    \\( A \\cap B = A \\)<br>\n\t\t    \\( A \\cup B = B \\)\n\t\t</td>\n\t</tr>\n\t</tbody>\n</table>"
			],

			"relationen": [
				"Seien `A` und `B` zwei beliebige Mengen. Eine (binäre) Relation `R` zwischen den Mengen `A` und `B` ist eine Teilmenge derProduktmenge `A xx B`:<br>`R sube A xx B`<br>Anstelle `(x,y) in R` schreibt man oft `R(x,y)` oder `xRy` und sagt: ”`x` steht inRelation `R` zu `y`“. `(x, y) notin R` wird auch bezeichnet durch `x(not R)y`.",
				"Sei `R sube A xx B` eine Relation zwischen `A` und `B`. Die inverse Relation `R^(−1) sube B xx A`, ist alsRelation zwischen `B` und `A` definiert durch `R^(−1) = {(y,x) in B xx A | (x,y) in R}`.",
				"Sei `R` eine Relation zwischen `A` und `B` und `S` eine Relation zwischen `C` und `D`. Das innere Produkt `R ox S` von `R`und `S` ist eine Relation zwischen `A xx C` und `B xx D`, die definiert ist als(R otimes S = {((a, c), (b, d)) in (A times C) times (B times D) mid aRb wedge cSd }).",
				"Sei `R` eine Relation zwischen `A` und `B`, und sei `S` eine Relation zwischen `B` und `C`. Die Komposition `R ◦ S` von `R` und`S` ist eine Relation zwischen `A` und `C`, für die gilt: `R ◦ S = {(a, c) in A xx C | ∃b in B : aRb ∧ bSc}`.",
				"<p>Sei `R` eine Relation über `A`</p>\n\t\t\n<table class=\"table table-striped table-condensed\">\n\t<thead>\n\t<tr>\n\t\t<td>Name</td>\n\t\t<td>Regel</td>\n\t</tr>\n\t</thead>\n\t<tbody>\n\t<tr>\n\t\t<td>reflexiv</td>\n\t\t<td>`AA x in A : xRx`</td>\n\t</tr>\n\t<tr>\n\t\t<td>symmetrisch</td>\n\t\t<td>`AA x, y in A : xRy = &gt; yRx`</td>\n\t</tr>\n\t<tr>\n\t\t<td>antisymmetrisch</td>\n\t\t<td>`AA x,y in A : xRy ^^ yRx = &gt; x = y`</td>\n\t</tr>\n\t<tr>\n\t\t<td>transitiv</td>\n\t\t<td>`AA x,y,z in A : (xRy ^^ yRz) = &gt; xRz`</td>\n\t</tr>\n\t<tr>\n\t\t<td>nacheindeutig</td>\n\t\t<td>`AA x,y,z in A : xRy ^^ xRz = &gt; y = z`</td>\n\t</tr>\n\t</tbody>\n</table>",
				"<p>Sei `R` eine Relation über `A` und sei `P` eine Eigenschaft von Relationen.\n   Die Relation `R^∗` heißt Abschluss von `R` bezüglich`P`, wenn gilt:</p>\n\n<ol>\n\t<li>`R^∗` besitzt die Eigenschaft `P`</li>\n\t<li>`R sube R^∗`</li>\n\t<li>Für alle Relationen `S`, die `R` umfassen und die die Eigenschaft `P` besitzen, gilt `R^∗ sube S`</li>\n</ol>\n\n<p>Häufig betrachtet wird der reflexive Abschluss, also der Abschluss einer Relation bzgl. der Eigenschaft der Reflexivität,\n   der symmetrische Abschluss und der transitive Abschluss einer Relation.\n   Besitzt eine Relation `R` bereits die Eigenschaft `P`, dann gilt natürlich `R^∗ = R` für den Abschluss `R^∗` dieser Relation bzgl. `P`.\n   Man sagt dann, dass `R` abgeschlossen ist bzgl. `P`.</p>",
				"Eine Äquivalenzrelation ist eine binäre Relation, die reflexiv, symmetrisch und transitiv ist.Bei Äquivalenzrelationen `R` schreibt man üblicherweise `x ∼_R y` oder `x ∼ y` anstelle von `xRy` und sagt, dass `x` und `y`äquivalent sind modulo `R`. Wenn keine Verwechslungen zu befürchten sind, wird `R` kurzerhand weggelassen.",
				"<p>Sei `A` eine nichtleere Menge.\n   Eine Zerlegung oder Partition von `A` ist eine Mengenfamilie `Z sube P(A)` mit</p>\n\n<ol>\n\t<li>`A = uuu Z`</li>\n\t<li>`O/ !in Z`</li>\n\t<li>Gilt `M_1, M_2 in Z` und `M1 != M2`, so folgt `M_1 nn M_2 = O/`</li>\n</ol>\n\n<p>Eine Zerlegung einer Menge `A` ist also eine Einteilung von `A` in nicht leere, paarweise elementfremde Teilmengen,\n   deren Vereinigung mit `A` übereinstimmt.\n   Die Elemente einer Zerlegung `Z` von `A` heißen Äquivalenzklassen oder kurz Klassen.\n   Eine Zerlegung selbst wird auch Klasseneinteilung genannt.</p>",
				"Sei `∼` eine Äquivalenzrelation über `A` und sei `a in A`. Dann bezeichnet `[a]_∼` die Äquivalenzklasse von `a` bezüglich `∼`,`[a]_∼ = {x in A | x∼a}`.Wenn keine Verwechslungen zu befürchten sind, wird nur kurz `[a]` geschrieben.Jede Äquivalenzklasse `[a]_∼` besteht aus sämtlichen Elementen, die sich, durch die Brille der Äquivalenzrelation `∼` gesehen,nicht unterscheiden lassen. `a ∼ b` gilt genau dann, wenn ihre Äquivalenzklassen `[a]_∼ = [b]_∼` übereinstimmen. Für dieRepräsentation einer Äquivalenzklasse ist es also vollkommen egal, welches Element man auswählt, alle erfüllen den selbenZweck mit vollkommen gleicher Eignung – aus Sicht der Äquivalenzrelation sind sie ja ununterscheidbar.",
				"Sei `∼` eine Äquivalenzrelation über einer nichtleeren Menge `A`. Die durch `∼` definierte Zerlegung von `A` wird mit `A // ∼`bezeichnetund (je nach Standpunkt) Quotientenmenge oder Faktormenge von `A` bezüglich `∼` genannt.",
				"Die Äquivalenzrelation `R′ ={(x,y) | ∃n∈N∃x_1...∃xn ∈A: x=x_1 ∧ y=x_n ∧ (x_i =x_(i+1) ∨ x_i R x_i + 1 ∨ x_i + 1 R x_i)`` \"für alle\" i = 1, 2, …, n−1}` heißt die durch `R` über `A` induzierte Äquivalenzrelation.",
				"Eine binäre Relation `R` über `A` heißt Halbordnungsrelation, falls `R` reflexiv, antisymmetrisch und transitiv ist.Bei Halbordnungsrelationen `R` schreibt man üblicherweise anstelle von `xRy` kurz `x ≤ y`.<br>Für `x ≤ y ∧ x != y` schreibt man kürzend `x < y`.",
				"Sei `≤` eine Halbordnungsrelation über `A`. Zwei Elemente `a, b in A` heißen vergleichbar bezüglich `≤`, falls `a ≤ b` oder `b ≤a` gilt. Unter den Halbordnungsrelationen sind diejenigen Relationen, bei denen alle Elemente der Grundmenge miteinandervergleichbarsind, der üblichen kleinergleich-Relation aus dem Reich der Zahlen am ähnlichsten.",
				"Eine Halbordnungsrelation `≤` über `A` heißt Ordnungsrelation, falls alle `x, y in A` vergleichbar bezüglich `≤` sind – d.h. fürzwei beliebige `x, y in A` gilt stets `x ≤ y` oder `y ≤ x`.",
				"Sei `≤` eine Halbordnungsrelation auf `A`. `a in A` heißt unmittelbarer Vorgänger von `b in A`, falls `a < b` und kein `c in A`existiertmit `a < c` und `c < b`. `b` wird unter diesen Umständen unmittelbarer Nachfolger von `a` genannt.Die Darstellung einer Halbordnungsrelation als Hasse-Diagramm besteht aus den Elementen der Grundmenge und Pfeilen von Elementenzu ihren direkten Nachfolgern.",
				"Sei `≤` eine Halbordnungsrelation auf `A` und sei `O/ != M sube A` eine nichtleere Teilmenge von `A`. Ein Element `m in M` heißtmaximales Element in `M`, wenn für alle `m′ in M` aus `m ≤ m′` folgt `m = m′`. `m` heißt minimales Element, wenn für alle `m′ inM` aus `m′ ≤ m` folgt `m = m′`.",
				"Sei `≤` eine Halbordnungsrelation auf `A` und sei `O/ != M sube A` eine nichtleere Teilmenge von `A`. Ein Element `a in A` heißtobere Schranke von `M` in `A`, wenn für alle `m in M` gilt `m ≤ a`.Eine minimale obere Schranke, also eine obere Schranke `a` mit `a ≤ a′` für alle oberen Schranken `a′` von `M` in `A`, heißtSupremum von `M` in `A`. Gilt `a in M` für das Supremum `a` von `M` in `A`, dann wird `a` Maximum von `M` genannt.Ein Element `a in A` heißt untere Schranke von `M` in `A`, wenn für alle `m in M` gilt `a ≤ m`.Eine maximale untere Schranke, also eine untere Schranke `a` mit `a′ ≤ a` für alle unteren Schranken `a′` von `M` in `A`, heißtInfimum von `M` in `A`. Gilt `a in M` für das Infimum `a` von `M` in `A`, dann heißt `a` Minimum von `M`.",
				"Sei `≤` eine Halbordnung über `A`.\n`K sube A` heißt Kette bzgl. `≤`, falls die auf `K` induzierte Halbordnung `≤K` eine Ordnungist.\n`K` heißtmaximale Kette in `A`, falls es keine `K` umfassende Kette in `A` bzgl. `≤` gibt.\n\n<table class=\"table table-striped table-condensed\">\n\t<caption>Operationen auf Relationen</caption>\n\t<thead>\n\t<tr>\n\t\t<td>`R = S`</td>\n\t\t<td>`∀(x,y) in AxxB:(xRy↔xSy)`</td>\n\t</tr>\n\t</thead>\n\t<tbody>\n\t<tr>\n\t\t<td>`RsubeS`</td>\n\t\t<td>`∀(x,y) in AxxB:(xRy→xSy)`</td>\n\t</tr>\n\t<tr>\n\t\t<td>`x(¬R)y`</td>\n\t\t<td>`∀(x,y) in AxxB:x(¬R)y↔¬(xRy)`</td>\n\t</tr>\n\t<tr>\n\t\t<td>`x(RuuS)y`</td>\n\t\t<td>`∀(x,y) in AxxB:(xRy∨xSy)`</td>\n\t</tr>\n\t<tr>\n\t\t<td>`x(RnnS)y`</td>\n\t\t<td>`∀(x,y) in AxxB:(xRy∧xSy)`</td>\n\t</tr>\n\t</tbody>\n</table>"
			],

			"Funktionen": [
				"Sei `F sube A xx B` eine Relation zwischen `A` und `B`.\n<ol>\n\t<li>`F` heißt linksvollständig, falls es zu jedem `a in A` ein `b in B` gibt, so dass`a F b`.</li>\n\t<li>`F` heißt rechtseindeutig, falls für alle Paare `(a, b), (a, b′) in A xx B` mit `a F b`und `a F b′` gilt `b = b′`.</li>\n</ol>",                    "Sei `F sube A xx B` eine linksvollständige und rechtseindeutige Relation. Dann heißt das Tripel `f = (A,B,F)` Abbildung von `A`nach`B`. Abbildungen werden meist geschrieben als `f : A → B`. Zwei Abbildungen `f = (A,B,F)` und `f′ = (A′,B′,F′)` sind gleich,wenn gilt `A = A′`, `B = B′` und `F = F′`.Ist `f = (A, B, F)` eine Abbildung, dann heißt `F` Graph von `f`. `A` ist der Definitionsbereich von `f` und `B` derWertebereich.Für jedes Element `a in A` des Definitionsbereichs von `f` bezeichnet man das eindeutig bestimmte Element `b in B` imWertebereich, für das gilt `a F b` mit `f(a)`. `f(a)` wird das Bild von `a` bei `f` genannt, `a` ist das Urbild. Die Zuordnungvon `a` zu `b` wird durch das Symbol `f : a 􏰨→ b` beschrieben.",
				"Eine Funktion ist eine Abbildung `f = (A, B, F )`, deren Wertebereich ein Zahlbereich ist. Eine zahlentheoretische Funktionist eine Funktion mit Werten im Bereich der ganzen Zahlen, eine reellwertige Funktion ist eine Funktion mit reellen Werten.",
				"Sei `f = (A,B,F)` eine Abbildung und seien `M sube A` und `N sube B` Teilmengen des Definitions- bzw. des Wertebereichs von `f`.Die Menge `f(M) = {b in B | EE m in M : b = f(m)}` heißt Bild von `M` unter `f`.In manchen Zusammenhängen wird anstelle `f(M)` auch `im_(f) M` geschrieben.`f(A)` wird auch Wertemenge von `f` genannt.Die Menge `f^(−1)(N) = {a in A | f(a) in N}` heißt Urbild von `N` unter `f`.Gilt `N = {b}`, dann schreibt man anstelle `f^(−1)({b})` kurz `f^(−1)(b)`.",
				"Sei `f = (A, B, F )` eine Abbildung und `M sube A` eine Teilmenge ihres Definitionsbereichs `A`. Die Abbildung `g = (M, B, F nn(M xx B))` heißt die Einschränkung von `f` auf `M`. `g` wird üblicherweise durch `f |_M` bezeichnet.",
				"Seien `f = (A,B,F)` und `g = (B,C,G)` zwei Abbildungen. Die Abbildung `(A, C, F ◦ G)` heißt Komposition oder auch Superpositionder Abbildungen `f` und `g` und wird durch `g ◦ f` bezeichnet. (Man beachte die vertauschte Reihenfolge.)",
				"Sei `f = (A, B, F )` eine Abbildung.<ol><li>`f` heißt surjektiv, falls `f(A) = B` gilt;</li><li>`f` heißt injektiv oder eineindeutig, falls für alle `a, a′ in A` gilt: `a != a′ => f(a) != f(a′)`;</li><li>`f` heißt bijektiv oder umkehrbar eindeutig, falls `f` surjektiv und injektiv ist.</li></ol>",
				"Sei `f : A → B` eine bijektive Abbildung. Die aufgrund des letzten Theorems zu `f` stets existierende Abbildung `g` mit`g ◦ f = id_A` und `f ◦ g = id_B` heißt die zu `f` inverse Abbildung oder Umkehrabbildung. Sie wird bezeichnet durch `f^(-1)`.Man überzeugt sich schnell, dass `f^(-1)` wieder eine bijektive Abbildung ist, und dass `(f^(-1))^(−1) = f` gilt.",
				"Eine endliche Folge mit Gliedern aus einer Menge `M` ist eine Abbildung `f:[n]→ M` von der Menge `[n] = {i in NN | i ≤ n} in M`.Eine unendliche Folge ist eine Abbildung `f : NN → M`.Gewöhnlich wird eine Folge f in der Form `(m_i)_(i in [n])` bzw. `(m_i)_(i in N)` aufgeschrieben,also als Abfolge der Folgenglieder `m_i = f(i)`.",
				"Sei `M` eine beliebige Menge und sei `I` eine nichtleere Menge.Eine Abbildung `f : I → M` heißt Indexfunktion von `I` nach `M`, `I` heißtIndexmenge. Die Werte `f(i)` einer Indexfunktion werden durch `mi` bezeichnet. `i` heißt Index von mi.Indexfunktionen werden gewöhnlich bezeichnet durch `(m_i)i in I` oder kurz `(m_i)`.Sind die Elemente `A` der indizierten Menge `M` Mengen, dann heißt `(A_i)` Mengenfamilie aus `M`.",
				"Sei `(A_i)_(i in I)` eine Familie von Teilmengen von `M`. Dann ist ` uuu_(i in I) A_i = { m | m in A_i \"für alle\" i in I}`und `uuu_(i in I) A_i = { m | m in A_i \"für ein\" i in I }`.Offensichtlich liefern die beiden Definitionen – wie in Kapitel 2 besprochen –genau Vereinigung und Durchschnitt, wenn die Indexmenge `I` endlich ist.",
				"Zwei Mengen `A` und `B` heißen gleichmächtig, falls es eine bijektive Abbildung `f` von `A` nach `B` gibt.Offensichtlich definiert die Gleichmächtigkeit eine Äquivalenzrelation zwischen Mengen. Endliche Mengen sind genau danngleichmächtig, wenn sie die gleiche Anzahl n von Elementen besitzen. Mit Hilfe des Begriffs der Gleichmächtigkeit lassen sich –und das ist eine der ganz großen Erkenntnisleistungen der mathematischen Logik – auch Vergleiche zwischen unendlichen Mengenziehen, die deutlich machen, dass es sehr verschiedene (nämlich unendlich viele) Arten von Unendlichkeit gibt. Das bekanntesteund erste Beispiel einer unendlichen Menge ist die Menge der natürlichen Zahlen N. Sie bestimmt die ”einfachste“ Art vonUnendlichkeit.",
				"Eine unendliche Menge `A` heißt abzählbar unendlich, wenn `A` und N gleichmächtig sind. `A` heißt abzählbar, wenn `A` endlich oder abzählbar unendlich ist.",
				"Eine Menge `M` heißt nicht abzählbar oder überabzählbar, wenn `M` nicht abzählbar ist."
			],

			"Beweisstrategien": [
				"Direkter Beweis",
				"Beweis durch Kontraposition",
				"Widerspruchs Beweis",
				"Äquivalenzbeweis",
				"Beweis durch Fallunterscheidung",
				"Beweis von Aussagen mit Quantoren",
				"Kombinatorischer Beweis"
			],

			"Induktion": [
				""
			],

			"Kombinatorik": [
				"Seien `A` und `B` endliche Mengen. Dann gilt: `#(A xx B) = #A * #B`.",
				"Sei `k` eine positive natürliche Zahl, und seien `A_1, A_2, …, A_k` endliche Mengen. Dann gilt: \n`#(A_1 xx A_2 xx … xx A_k) = prod_(i=1)^k #A_i`",
				"Seien `A` und `B` paarweise disjunkte endliche Mengen. Dann gilt: `#(A uu B) = #A + #B`.",
				"Sei `k` eine positive natürliche Zahl, und seien `A_1, A_2, …, A_k` paarweise disjunkte endliche Mengen. Dann gilt: `#uuu_(i=1)^k A_i = sum_(i=1)^k #A_i`",
				"Seien `A` und `B` endliche Mengen. Dann gilt: `#(A uu B) = #A + #B − #(A nn B)` (Inklusions-Exklusionsprinzip)",
				"Seien `A`, `B` und `C` endliche Mengen. Dann gilt: `#(A uu B uu C)``= #A + #B + #C − #(A nn B) − #(A nn C) − #(B nn C) + #(A nn B nn C)`",
				"Eine Anordnung aller Elemente einer endlichen Menge heißt Permutation.",
				"Die Anzahl aller Permutationen einer `n`-elementigen Menge `S` ist `n!`.",
				"Eine k-Permutation einer endlichen Menge `S` ist eine Permutation einer `k`-elementigen Teilmenge von `S`.",
				"Wir bezeichnen mit `[(n),(k)]` die Anzahl aller `k`-Permutationen einer `n`-elementigen Menge.",
			    "Seien `n` und `k` natürliche Zahlen mit `n >= k >= 1`.\nFür die Anzahl aller `k`-Permutationen einer `n`-elementigen Menge gilt: `[(n),(k)] = n * ( n − 1 ) * … * ( n − k + 1 )`",
				"Für alle natürlichen Zahlen `n` und `k` mit `n >= k >= 1` gilt: `[(n),(k)]= (n!)/((n−k)!)`",
				"`((n),(k))` bezeichnet die Anzahl der k-elementigen Teilmengen einer n-elementigen Menge. `((n),(k))` wird \"`n` über `k`\" ausgesprochen und auch Binomialkoeffizient von `n` und `k` genannt.",
				"Seien `k` und `n` natürliche Zahlen mit `k ≤ n`.\nFür die Anzahl `((n),(k))` der `k`-elementigen Teilmengen einer `n`-elementigen Menge gilt: <br>\n`((n),(k)) = (n · (n−1) * … * (n−k+1))/(k!)`",
				"<strong>Pascal'sche Gleichung:</strong><p>Für alle natürlichen Zahlen `k` und `n` mit `1 <= k <= n` gilt:</p> `((n),(k)) = ((n-1),(k-1)) + ((n-1),(k))`",
				"<strong>Gleichung von Vandermonde</strong>\n<p>Für alle natürlichen Zahlen `k`, `m` und `n` mit `k <= m` und `n <= m` gilt:</p>\n`((m+n),(k)) = sum_(i=0)^k ((m),(i)) * ((n),(k-i))`",
				"<p>Für alle natürlichen Zahlen `k` und `n` gilt:</p>\n`((n+1),(k+1)) = sum_(i=0)^n ((i),(k))`",
				"<p>Für alle natürlichen Zahlen `k` und `n` mit `k <= n` gilt:</p>\n`((n+1),(k)) = sum_(i=0)^n ((n-i),(k-i))`",
				"<strong>Binomischer Satz:</strong>\n<p>Für alle natürlichen Zahlen `n` gilt:</p>\n`(x+y)^n = sum_(j=0)^n ((n),(j)) * x^(n-j) * y^j`",
				"<p>Für alle natürlichen Zahlen `n` gilt:</p>\n`sum_(i=0)^n (-1)^i * ((n),(i)) = 0`",
				"<p>Für alle natürlichen Zahlen `n` gilt:</p>\n`sum_(i=0)^n ((n),(i)) = 2^n`",
				"<p>Für alle natürlichen Zahlen `r` und `k` gilt:</p>\n`((r),(k)) = (-1)^k * ((k-r-1),(k))`",
				"<strong>Stirlingsche Formel:</strong>\n<p>Für alle natürlichen Zahlen `n` gilt:</p>\n`sqrt(2 pi n) * (n / e)^n <= n! <= sqrt(2 pi n) * (n / e)^n * e^(1/(12n))`<br>\n\t\t\n<strong>Korollar:</strong>\n<p>Für alle natürlichen Zahlen `n` und `k` gilt:</p>\n`(n / k)^k <= ((n),(k)) <= ((e * n)/ k)^k`"
			],

			"Stochastik": [
				"Eine abzählbare Menge `S` heißt Ereignisraum",
				"Sei `S` ein Ereignisraum. Eine Teilmenge `E sube S` heißt Ereignis.",
				"<p>Sei S ein Ereignisraum.\nEine Wahrscheinlichkeitsverteilung ist eine Funktion `Prob : P(S) -> RR` mit folgenden Eigenschaften:</p>\n<ol>\n\t<li>`sf \"Prob\"(E) ≥ 0` für jedes Ereignis `E sube S` </li>\n\t<li>`sf \"Prob\"(S) = 1`</li>\n\t<li>`sf \"Prob\"(E) = sum_(e in E) sf \"Prob\"({e})` für jedes Ereignis `E sube S`</li>\n</ol>",
				"<p>Sei S ein Ereignisraum und `P` eine Funktion `P : S -> RR` mit folgenden Eigenschaften:</p>\n<ol>\n\t<li>`P(e) >= 0` für jedes elementare Ereignis `e in S`</li>\n\t<li>`sum_(e in S) P(e) = 1`</li>\n</ol>\n\nSei die Funktion `sf \"Prob\" : P(S) -> RR` definiert durch `sf \"Prob\"(E) = sum_(e in E) P(e)` für alle `E sube S`.\nDann ist `sf \"Prob\"` eine Wahrscheinlichkeitsverteilung auf `S`.",
				"<p>Die bedingte Wahrscheinlichkeit von Ereignis `A` unter der Voraussetzung, dass Ereignis `B` eintritt, ist definiert als</p>\n`sf \"Prob\"(A|B) = (sf \"Prob\"(A ∩ B)) / (sf \"Prob\"(B))`",
				"<strong>Satz von Bayes</strong>\n<p>Seien `A` und `B` zwei Ereignisse, dann gilt:</p>\n`sf \"Prob\"(A|B) = (sf \"Prob\"(A) * sf \"Prob\"(B|A))/(sf \"Prob\"(B))`",
				"Eine Zufallsvariable `X` ist eine Funktion aus einem Ereignisraum `S` in die reellen Zahlen, `X : S -> RR`.",
				"<p>Sei `S` ein Ereignisraum, `sf \"Prob\"` eine Wahrscheinlichkeitsverteilung von `S` und `X` eine Zufallsvariable auf `S`.\n   Die Wahrscheinlichkeit, dass `X` den Wert `r` annimmt, ist</p>\n   `sf \"Prob\"[X = r] = sum_(e in X^(-1) (r)) sf \"Prob\"({e})`",
				"<p>Sei `S` ein Ereignisraum und `X` eine Zufallsvariable auf `S`. Der Erwartungswert von `X` ist folgendermaßen definiert:\n   `E[X] = sum_(r in X(S)) r * sf \"Prob\"[X=r]`</p>",
				"<strong>Ungleichung von Markoff:</strong>\n<p> Sei `c > 0` und `X` eine Zufallsvariable, die keinen negativen Wert annimmt. Dann gilt:</p>\n`sf \"Prob\"[X >= c] <= (E[X]) / c`\n",
				"<p>Die Varianz `Var[X]` einer Zufallsvariablen `X` ist der Erwartungswert</p>\n`Var[X] = E[(X − E[X])^2]`\n<p>Die (positive) Quadratwurzel `sqrt(Var[X])` der Varianz heißt Standardabweichung von `X`</p>",
				"<p>Seien `X` und `Y` Zufallsvariablen über dem Ereignisraum `S`, und `k` sei in `RR`. Dann gilt:</p>\n\n<ol>\n\t<li>`E[k] = k`</li>\n\t<li>`E[E[X]] = E[X]`</li>\n\t<li>`E[k * X] = k * E[X]`</li>\n\t<li>`E[X + Y] = E[X] + E[Y]`</li>\n\t<li>`E[X * E[X]] = E[X]^2`</li>\n</ol>",
				"<p>Sei `X` eine Zufallsvariable. Dann gilt:</p>\n`Var[X] = E[X^2] − E[X]^2`",
				"<strong>Ungleichung von Tschebyscheff:</strong>\n<p>Sei `X` eine Zufallsvariable und `c > 0`. Dann gilt:</p>\n`sf \"Prob\"[(X - E[X])^2 >= d] <= (Var[X])/d`",
				"<p>Für die Wahrscheinlichkeit `b(k, n, p)`, bei `n` unabh ̈angigen Bernoulli Versuchen mit Erfolgswahrscheinlichkeit `p`\n   genau `k`-mal Erfolg zu haben, gilt:</p>\n`b(k; n, p) = ((n),(k)) * p^k * q^(n-k)`",
				""
			],

			"Boolesche Algebra": [
				"<p>Die Menge aller n-stelligen Boole’schen Ausdrücke ist induktiv definiert durch:</p>\n<ol>\n\t<li>Die Konstanten `0` und `1` sowie die Boole’schen Variablen `x_1, …, x_n` sind `n`-stellige Boole’sche Ausdrücke.</li>\n\t<li>Sind `alpha` und `beta` `n`-stellige Boole’sche Ausdrücke, dann sind auch `bar(alpha)`, `(alpha + beta)` und `(alpha * beta)`\n\t    `n`-stellige Boole’sche Ausdrücke.</li>\n</ol>\n<p>Die Stelligkeit eines Boole’schen Ausdrucks gibt also an, welche Boole’schen Variablen in ihm vorkommen können.</p>",
				"<p>Jeder `n`-stellige Boole’sche Ausdruck `alpha` stellt eine `n`-stellige Schaltfunktion `f : bbb B^n -> bbb B` dar.\n   Man erhält den Wert von `f` für das Argument `(b_1, …, b_n)`,\n   indem im Boole’schen Ausdruck `alpha` die Variable `x_1` durch den Wert `b_1, …,` die Variable `x_n` durch den Wert `b_n` ersetzt\n   und den Wert des so erhaltenen Ausdrucks nach den Boole’schen Operationen berechnet.</p>",
				"<p>Zwei Boole’sche Ausdrücke `alpha` und `beta` heißen  ̈aquivalent genau dann, wenn sie dieselbe Schaltfunktion darstellen.</p>",
				"<p>Eine Boole’sche Algebra besteht aus:</p>\n<ol>\n\t<li>Einer Grundmenge `bbb B`</li>\n\t<li>Den zweistelligen Operationen `o+` (Summe) und `ox` (Produkt) auf `bbb B`</li>\n\t<li>Der einstelligen Operation `kappa` (Komplement) auf `bbb B`</li>\n\t<li>Den beiden unterschiedlichen Elementen `ul 0` und `ul 1` in `bbb B`</li>\n</ol>\n<p>Eine Boole’sche Algebra wird durch das Quadrupel (`bbb B`,`o+`, `ox`, `kappa`) bezeichnet.</p>\n<p>Die Grundmenge `bbb B` muss aus mindestens zwei Elementen mit den in den Neutralitäts- und Komplementgesetzen geannten Eigenschaften\n   bestehen: Ein Element `ul 0` und ein anderes `ul 1`. Diese beiden Elemente von `bbb B` sind das\n   Nullelement und das Einselement.</p>",
				"<table class=\"table table-striped table-condensed\">\n\t<caption>Rechengesetze für alle Elemente a, b und c in der Grundmenge B</caption>\n\t<tr>\n\t\t<td>Kommutativgesetz</td>\n\t\t<td>`a o+ b = b o+ a`<br>\n\t\t    `a ox b = b ox a`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Distributivgesetz</td>\n\t\t<td>`a ox (b o+ z) = a ox b o+ a ox z`<br>\n\t\t    `a o+ (b ox z) = (a o+ b) ox (a o+ z)`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Neutralitätsgesetz</td>\n\t\t<td>`a o+ ul 0 = a`<br>\n\t\t    `a ox ul 1 = a`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Komplementgesetz</td>\n\t\t<td>`a o+ kappa(a) = ul 1`<br>\n\t\t    `a ox kappa(a) = ul 0`\n\t\t</td>\n\t</tr>\n</table>",
				"<p>Das Nullelement und das Einselement in einer Boole’schen Algebra sind eindeutig bestimmt.</p>",
				"<p>Sei `(bbb B, o+, ox, kappa, ul 0, ul 1)` eine Boole’sche Algebra.\n   Eine `n`-stellige Funktion `f : B_n -> B` heißt Boole’sche Funktion,\n   wenn es einen `n`-stelligen Boole’schen Ausdruck `alpha` mit der folgenden Eigenschaft gibt:</p>\n\n<p>Den Wert von `f` für das Argument `(b_1, …, b_n)` erhält man,\n   indem man im Ausdruck `alpha` folgende Schritte ausführt\n   und den Wert des so erhaltenen Ausdrucks nach den Definitionen von `o+`, `ox` und `kappa` berechnet.</p>\n\n<ol>\n\t<li>Die Variable `x_1` durch den Wert `b_1, …,` die Variable `x_n` durch den Wert `b_n` ersetzt</li>\n\t<li>Die Konstante `0` durch das Nullelement und die Konstante `1` durch das Einselement ersetzt</li>\n\t<li>jedes Operationszeichen `+` durch ein `o+`</li>\n\t<li>jedes Operationszeichen `*` durch ein `ox` und</li>\n\t<li>jedes Operationszeichen `bar` durch ein `kappa` ersetzt</li>\n</ol>",
				"<p>Sei `(bbb B, o+, ox, kappa, ul 0, ul 1)` eine endliche Boole’sche Algebra.\n   Die Operation `o+` ist idempotent, das heißt es gilt `x o+ x = x` für jedes Element `x in bbb B`.</p>",
				"<strong>Dualit ̈atsprinzip</strong>\n<p>Gilt eine Eigenschaft in der Boole’schen Algebra, dann gilt auch die duale Eigenschaft.</p>  ",
				"<p>Sei `(B, o+, ox, kappa, ul 0, ul 1)` eine endliche Boole’sche Algebra.\n   Für alle Elemente `a`, `b` und `c` in `B` gelten die folgenden Aquivalenzen:</p>\n\n<table class=\"table table-striped table-condensed\">\n\t<tr>\n\t\t<td>Dominanzgesetz</td>\n\t\t<td>`a o+ ul 1 = ul 1`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Absorptionsgesetz</td>\n\t\t<td>`a o+ (a ox b) = a`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Gesetz zur Vereinfachung von Gleichungen</td>\n\t\t<td>Wenn `b o+ a = c o+ a` und `b o+ kappa(a) = c o+ kappa(a)`\n\t\t    dann ist `b = c`\n\t\t</td>\n\t</tr>\n\t<tr>\n\t\t<td>Assoziativgesetz:</td>\n\t\t<td>`a o+ (b o+ c) = (a o+ b) o+ c`</td>\n\t</tr>\n\t<tr>\n\t\t<td>deMorgan’sches Gesetz</td>\n\t\t<td>`kappa(a o+ b) = kappa(a) ox kappa(b)`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Eindeutigkeit des Komplements:</td>\n\t\t<td>Wenn `a o+ b = ul 1` und `a ox b = ul 0`, dann ist `b = kappa(a)`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Komplementarit ̈at der neutralen Elemente</td>\n\t\t<td>`bar ul 0 = ul 1`, `bar ul 1 = ul 0`</td>\n\t</tr>\n\t<tr>\n\t\t<td>Doppelnegationsgesetz:</td>\n\t\t<td>`kappa(kappa(a)) = a`</td>\n\t</tr>\n</table>",
				"<p>Sei `(B, o+, ox, kappa, ul 0, ul 1)` eine Boole’sche Algebra.\n   Dann ist `(B, <=)` eine Halbordnung auf der Grundmenge `B`.</p>",
				"<p>`x <= y` genau dann, wenn `x ox y = x`.</p>",
				"<p>`x <= y` genau dann, wenn `kappa(x) o+ y = ul 1`.</p>",
				"<p>Ein Atom einer Boole’schen Algebra `(B, o+, ox, kappa, ul 0, ul 1)` ist ein Element `a in B` mit folgenden Eigenschaften:\n   `a != ul 0`, und für alle `b <= a` gilt:<br>\n   `b = ul 0` oder `b = a`.</p>",
				"<p>Sei `a` ein Atom einer Boole’schen Algebra, und `b` sei ein beliebiges Element aus deren Grundmenge.\n   Dann gilt: `a ox b = ul 0` oder `a ox b = a`.",
				"<p>Sei `a` ein Atom einer Boole’schen Algebra, und `b` ein beliebiges Element aus deren Grundmenge.\n   Dann gilt: `a ox b = ul 0` genau dann, wenn `a ox kappa(b) = a`.</p>",
				"<p>Sei `a` ein Atom einer Boole’schen Algebra, und `b` ein beliebiges Element aus deren Grundmenge.\n   Dann gilt: `a <= b` oder `a <= kappa(b)`</p>",
				"<p>Jedes Element `a` einer Boole’schen Algebra ist die Summe der Atome, die kleiner oder gleich `a` sind.</p>",
				"<p>Jedes Element einer Boole’schen Algebra ist eindeutig als Summe von Atomen darstellbar.</p>",
				"<p>Besitzt eine Boole’sche Algebra `n` Atome, dann besitzt sie genau `2^n` Elemente.</p>",
				"<p>Jedes Element einer Boole’schen Algebra ist das Produkt aller größeren Atomkomplemente.</p>"
			]
		}
	}
}