apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: educatopia-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: educatopia
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production

            - name: MONGODB_HOST
              value: educatopia-mongo-service

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: educatopia-secrets
                  key: SESSION_SECRET

            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: educatopia-secrets
                  key: SENDGRID_API_KEY

          image: gcr.io/deploy-219812/educatopia:latest
          name: educatopia-container
          ports:
            - containerPort: 3470
      restartPolicy: Always
